<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Blog</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
    <script src="js/admin.js" defer></script>
</head>
<body>
    <header>
        <h1>Dashboard Administration Blog</h1>
        <h4>Site Public ?????</h4>
    </header>
    <main>
        <section>
           <form action="add_article.php" method="POST">
                <input type="submit" value="+ Nouvel article" class="btn">
            </form>
            <caption>Liste des articles</caption>
            <table>
            <thead>
                <tr>
                    <th scope="col">Titre</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Image</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
                <tbody>
                <?php foreach ($articles as $article): ?>
                    <tr>
                        <td><?=$article['title'];?></td>
                        <td><?=(new DateTimeImmutable($article['createdAt']))->format('d/m/Y');?></td>
                        <td>
                            <?php if ($article['image']): ?>
                                <img src="images/<?=$article['image'];?>" alt="">
                            <?php endif; ?>
                        </td>
                        <td>
                            <a href="edit_article.php?id=<?=$article['id'];?>"><i class="fa-solid fa-pen-to-square"></i> Modifier</a>
                         
                            <a class="delete-article-button" href="delete_article.php?id=<?=$article['id'];?>"><i class="fa-solid fa-trash-can"></i> Supprimer</a>
                         </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </section>
    
    </main>
</body>
</html>