<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire modification d'article</title>
</head>
<body>
<header>
        <h1>Modification article</h1>
    </header>
    <main>
        <h2>PAGE ARTICLE en modification</h2>
        <form method="POST" action="edit_article.php">
            <fieldset>
                <legend>Modifier un article</legend>
                <div>
                    <label for="title">Titre de l'article</label>
                    <input type="text" id="title" name="title" value=<?=$article['title'];?>>
                    <?php if (isset($errors['title'])): ?>
                        <p class="error"><?=$errors['title'];?></p>
                    <?php endif; ?>
                </div>
                <div>
                    <label for="abstract">Résumé de l'article</label>
                    <textarea id="abstract" name="abstract"><?=$article['abstract'];?></textarea>
                </div>
                <div>
                    <label for="content">Contenu de l'article</label>
                    <textarea id="content" name="content"><?=$article['content'];?></textarea>
                    <?php if (isset($errors['content'])): ?>
                        <p class="error"><?=$errors['content'];?></p>
                    <?php endif; ?>
                </div>
                <div>
                    <label for="image">Image</label>
                    <input type="text" id="image" name="image" value=<?=$article['image'];?>>
                </div>
                <input type="submit" value="Modifier">
            </fieldset>
        </form>
    </main>
</body>
</html>